version: "3"
services:
  pwn:
    build: .
    restart: always
    volumes:
      - ~/ctf:/ctf
    container_name: pwnbox
    stdin_open: true
    tty: true
    environment:
      - http_proxy=http://172.20.0.1:7777
      - https_proxy=http://172.20.0.1:7777
    cap_add:
            - SYS_PTRACE
    security_opt:
            - seccomp:unconfined
