version: "3"
services:
  pwn:
    build: .
    restart: always
    volumes:
      - ~/ctf:/ctf
      - ~/local:/local
    container_name: pwnbox
    stdin_open: true
    tty: true
    environment:
      - http_proxy=
      - https_proxy=
    cap_add:
            - SYS_PTRACE
    security_opt:
            - seccomp:unconfined
